import "../styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "../trpc/react";
import { Header } from "./_components/Header";
import { auth } from "../server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  const isLoggedIn = !!session?.user;

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className={`${isLoggedIn ? "bg-[#f9fafb]" : "bg-[#f5f6ee]"} text-gray-900`}>
        <TRPCReactProvider>
          {isLoggedIn ? (
            <>
              {children}
            </>
          ) : (
            <>
              <Header />
              {children}
            </>
          )}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
